# Copyright (c) 2020-2021 MeteoSwiss, created by F.P.A. Vogt; frederic.vogt@meteoswiss.ch
# Adjusted from dvas to brutifus in March 2021 by F.P.A. Vogt; frederic.vogt@alumni.anu.edu.au

name: CI_docs_check

on:
  # Executed on push to Master in the odd even that the docs is modified straight from there.
  push:
    branches: [ master ]
  pull_request:
    branches: [ master, develop ]

jobs:
  docs:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.8]

    steps:
      # Checkout our repository
      - name: Checkout current repository
        uses: actions/checkout@v2

      # Set up Python
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      # Install any dependency we require for the docs
      - name: Install dependancies
        run: |
          python -m pip install --upgrade pip
          python -m pip install sphinx
          python -m pip install sphinx-rtd-theme
        shell: bash

      # Here, let's install our module to make sure all the dependencies specified in setup.py are
      # also installed
      - name: Install our module
        run: pip install -e .
        shell: bash

      # Launch a home-made python script to compile and check the docs.
      - name: Compile the docs and look for errors/warnings
        run: |
          cd ./docs
          python ../.github/workflows/docs_check.py

        shell: bash
